model_type: HeteroRGCN
ntype_dict:
  node1: 100
  node2: 150
etypes: ['rel1', 'rel2']
in_size: 16
hidden_size: 32
out_size: 10
n_layers: 3
embedding_size: 16
dropout_rate: 0.5
use_residual: true
use_bn: true
layer_type: gat  # Options: 'linear', 'conv', 'gat'
num_heads: 4         # Only used if layer_type is 'gat'
